services:
  backend:
    container_name: backend
    build: backend
    image: python:latest
    ports:
      - "4000:4000"

  frontend:
    container_name: frontend
    build: frontend
    ports:
      - "3000:3000"